trigger:
- main  # Make sure this matches the branch name in your repo

pool:
  name: Default  # Your self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  NUGET_FEED_URL: 'https://pkgs.dev.azure.com/jlenis/StringExtensionsCI/_packaging/string-extension-feed/nuget/v3/'

steps:
# Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true

# Install NuGet CLI
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet CLI'

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: 'StringExtensionsLibrary/StringExtensionsLibrary.csproj'

# Build the solution
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: 'StringExtensionsLibrary/StringExtensionsLibrary.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Pack NuGet package
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: 'StringExtensionsLibrary/StringExtensionsLibrary.csproj'
    configuration: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'

# Push to Azure Artifacts feed (using dotnet with Azure Artifacts Credential Provider)
- script: |
    echo "Pushing NuGet package to Azure Artifacts..."
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" --source "$(NUGET_FEED_URL)" --api-key $(NUGET_PAT)
  displayName: 'Push to Azure Artifacts feed'
  env:
    NUGET_PAT: $(NUGET_PAT)  # Make sure you have the NUGET_PAT variable set in the pipeline variables or as a secret.
