# azure-pipelines.yml

trigger:
- main  # Change to your default branch if needed

pool:
  name: Default  # Self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  NUGET_FEED_URL: 'https://pkgs.dev.azure.com/jlenis/StringExtensionsCI/_packaging/string-extension-feed/nuget/v3/index.json'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet CLI'

# Optional: Debugging step to verify .nupkg generation path
- script: |
    echo "Before pack - contents of staging dir:"
    dir $(Build.ArtifactStagingDirectory)
  displayName: 'Debug: Show staging dir before pack'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: 'StringExtensionsLibrary/StringExtensionsLibrary.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: 'StringExtensionsLibrary/StringExtensionsLibrary.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: 'StringExtensionsLibrary/StringExtensionsLibrary.csproj'
    configuration: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'

# Optional: Confirm package is generated
- script: |
    echo "After pack - contents of staging dir:"
    dir $(Build.ArtifactStagingDirectory)
  displayName: 'Debug: Show staging dir after pack'

- script: |
    echo "Pushing NuGet package to Azure Artifacts..."
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source $(NUGET_FEED_URL) --api-key az
  displayName: 'Push to Azure Artifacts feed'
  env:
    VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"$(NUGET_FEED_URL)","username":"AzureDevOps","password":"$(NUGET_PAT)"}]}'
    NUGET_PAT: $(NUGET_PAT)
